### ISSUE TITLE
[Windows 11 ARM64]: Agent upgrade failed while upgrading Windows agent from 9.2.2 SNAPSHOT to 9.3.0 SNAPSHOT.

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/elastic-agent#11672]
**Kibana Build details:**
```
VERSION: 9.3.0 SNAPSHOT
BUILD: 94200
COMMIT: 36db4d9d2879c273b327342197440300198d6fb7
```

**Host OS:**  All

**Preconditions:**
1. 9.3.0 SNAPSHOT Kibana should be available.
2. Agent Policy should be created.
3. Windows ARM64 agent (v9.2.2) should be installed.
4. 9.2.2 SNAPSHOT agent binary should be added.

**Steps to reproduce:**

1. Navigate to Fleet>Agents tab.
2. Upgrade Windows Arm agent from 9.2.2 to 9.3.0 SNAPSHOT.
3. Observe agent starts upgrading and after sometime fails.
4. Navigate to Agents Logs.
5. Observe that error is displayed for upgrade failed.
 ```
download attempt 3 failed: unable to download package: generating package name failed: 'windows-binary-arm64' is not a valid combination for a package
generating package name failed: 'windows-binary-arm64' is not a valid combination for a package
generating package name failed: 'windows-binary-arm64' is not a valid combination for a package; retrying in 43.311678001s.
```

**Note:** This issue is also reproducible when upgrading a standalone agent.

**Expected Result:**

- Windows ARM64 agent should successfully upgrade from 9.2.2 SNAPSHOT → 9.3.0 SNAPSHOT without falling back to an older version.
- Standalone agent upgrade should also complete successfully for Windows ARM64.

**Screen-shot**
- Fleet Tab

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/d5085354-643e-4f75-8883-c1e473b3715d" />

- Agents Logs Tab

<img width="1898" height="813" alt="Image" src="https://github.com/user-attachments/assets/57c5eb1f-79e0-4be4-ba13-c83558434b74" />

- Standalone Agent 

<img width="1472" height="700" alt="Image" src="https://github.com/user-attachments/assets/dc160e2d-e827-438b-82ce-72864edf808e" />

**Agent Logs:**

[elastic-agent-diagnostics-2025-12-08T10-20-50Z-00.zip](https://github.com/user-attachments/files/24029753/elastic-agent-diagnostics-2025-12-08T10-20-50Z-00.zip)

**Ticket:**
https://github.com/elastic/ingest-dev/issues/6543

**Comment by harshitgupta-qasource** [comment]
@amolnater-qasource Kindly review

**Comment by amolnater-qasource** [comment]
Secondary review for this ticket is Done.

**Comment by pierrehilbert** [comment]
We should update the list here: 
https://github.com/elastic/elastic-agent/blob/a8bbcf66d38f2941587611f4ba6db3b2494be16d/internal/pkg/agent/application/upgrade/artifact/artifact.go#L15-L25

**Comment by pierrehilbert** [comment]
I opened a PR. https://github.com/elastic/elastic-agent/pull/11673
cc @ebeahan

**Comment by nimarezainia** [comment]
Can we close this issue now as resolved? (thank you)

**Comment by pierrehilbert** [comment]
It should be the case, @harshitgupta-qasource could you please run the manual testing again to confirm this is now fixed?

**Comment by harshitgupta-qasource** [comment]
Hi Team,

We have re-validated this issue on the latest 9.3.0 BC1 Kibana cloud environment and found that the issue is **still reproducible**

**Observations:**
- Windows ARM64 agent is not upgrading from 9.2.3 → 9.3.0 BC1 and fails after some time.
- Standalone agents on Windows ARM64 are also not upgrading successfully.

**Build Details**
VERSION: 9.3.0 BC1
BUILD: 94822
COMMIT: c42e4abbd81ade41addc00964fc7a8d38a2c739d
Artifact: https://staging.elastic.co/9.3.0-0ca7f097/summary-9.3.0.html

**Screenshot**
- Agents Logs Tab

<img width="1918" height="873" alt="Image" src="https://github.com/user-attachments/assets/088f5342-e63c-4158-b7fe-dc8fea671e4d" />

- Agents Tab 

<img width="1483" height="808" alt="Image" src="https://github.com/user-attachments/assets/f90108b0-d8d8-4d1d-944e-4f8a30e66885" />

- Standalone Agent  

<img width="1455" height="471" alt="Image" src="https://github.com/user-attachments/assets/e2c754a2-7cf5-4894-b63b-7b67475fbc84" />

**Agent Logs:**
- Agents: 

[elastic-agent-diagnostics-2025-12-23T13-11-08Z-00.zip](https://github.com/user-attachments/files/24311242/elastic-agent-diagnostics-2025-12-23T13-11-08Z-00.zip)

- **Standalone Agent:**  

[elastic-agent-diagnostics-2025-12-23T12-29-20Z-00.zip](https://github.com/user-attachments/files/24311243/elastic-agent-diagnostics-2025-12-23T12-29-20Z-00.zip)

- **Snapshot Agents Logs:**

[elastic-agent-diagnostics-2025-12-23T13-41-56Z-00.zip](https://github.com/user-attachments/files/24311523/elastic-agent-diagnostics-2025-12-23T13-41-56Z-00.zip)

Note: Agent upgrade also failed on latest snapshot build

Kindly let us know if anything else is required from our end.
Thanks

**Comment by pierrehilbert** [comment]
My bad: it will continue to fail on 9.2.3 upgrade because the fix is in 9.3.0.
We should try to upgrade from 9.3.0 to 9.3.0-SNAPSHOT for example if we want to test the upgrade process.
Or we need to backport my fix to 9.2 branch.

**Comment by harshitgupta-qasource** [comment]
Hi @pierrehilbert ,

> We should try to upgrade from 9.3.0 to 9.3.0-SNAPSHOT for example if we want to test the upgrade process.

We attempted to upgrade the 9.3.0 BC1 agent > 9.3.0-SNAPSHOT on the latest 9.3.0 BC1 Kibana cloud environment through the API, and the agent upgrade completed successfully.
We have attached the relevant screenshots and agent logs for reference.

**Screen shot:**

<img width="1327" height="763" alt="Image" src="https://github.com/user-attachments/assets/174166fa-8e96-4caf-a17f-e518646b32de" />

<img width="1572" height="760" alt="Image" src="https://github.com/user-attachments/assets/970eca51-f6e1-43cf-96d2-736e26e41322" />

<img width="1557" height="547" alt="Image" src="https://github.com/user-attachments/assets/7cc7d5f9-a4c9-4a11-90b7-fa9195299c4f" />

- Standalone Agent

<img width="1275" height="275" alt="Image" src="https://github.com/user-attachments/assets/a67fa116-6cf7-49eb-b554-2db0393d9822" />

**Agent Logs:**

[elastic-agent-diagnostics-2025-12-24T05-52-35Z-00.zip](https://github.com/user-attachments/files/24323098/elastic-agent-diagnostics-2025-12-24T05-52-35Z-00.zip)

Kindly let us know if anything else is required from our end.
Thanks

**Comment by nimarezainia** [comment]
@harshitgupta-qasource I assume that this works for other binaries correct? (say different architectures)

@pierrehilbert since at best Windows 11 ARM may be available from 9.3 onward, the 9.2 to 9.3 upgrade path is irrelevant. I don't see a reason to backport your fix to 9.2, unless you believe it's a low risk thing to do. (looking at the diffs that may be the case).

**Comment by harshitgupta-qasource** [comment]
Hi @nimarezainia 
> @harshitgupta-qasource I assume that this works for other binaries correct? (say different architectures)

Yes, we validated this on the Windows x86_64 architecture. 
We triggered the agent upgrade from 9.2.3 → 9.3.0 BC1, and the upgrade completed successfully.

Please let us know if anything else is required from our side.
Thanks

**Comment by ebeahan** [comment]
Based on the last comments, I believe this issue is safe to close. Feel free to re-open if that's incorrect.

**Comment by nimarezainia** [comment]
so can we claim agent on windows arm supported? and get the binary up on the download site

**Comment by harshitgupta-qasource** [comment]
Hi team ,

We have revalidated this ticket on the latest 9.4.0-SNAPSHOT Kibana cloud environment and found it  **working fine as expected**

**Observations:**

-  Windows ARM64 agents are successfully upgrade from 9.3.0 → 9.4.0 SNAPSHOT 

**Build Details:**
```
VERSION: 9.4.0 SNAPSHOT
BUILD: 97528
COMMIT: bdba8dc7f7ce1c391efc794a96d9118ea03b4e3c
```
**Screenshot:**
-  Fleet Managed Agent

<img width="1911" height="578" alt="Image" src="https://github.com/user-attachments/assets/1fe70d79-358f-4659-b0cf-b3e6ade9655f" />

-  Standalone Agent 

<img width="1297" height="241" alt="Image" src="https://github.com/user-attachments/assets/db9d9b88-c409-4730-9c14-2cc55b460433" />

Hence, we are marking this issue as **QA:Validated.**
Thanks!
