### ISSUE TITLE
[Self-Managed]: No data under data streams tab for secondary agent installed on self-managed kibana having Fleet Server running.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#1861]
**Kibana version:**  8.6 BC4 kibana self-managed environment

**Host OS and Browser version:** All, All

**Build details:**
```
VERSION: 8.6.0 BC4 Kibana self-managed environment
BUILD: 58612
COMMIT: 218162f282314db5b3833c84752dd24395949b3f
```

**Preconditions:**
1. 8.6 BC4 kibana self-managed environment should be available.
2. Fleet Server should be installed.

**Steps to reproduce:**
1. Navigate to Agents tab.
3. Create Agent policy and run agent install command with `--insecure`.
4. Observe agent is installed on self-managed environment, however remains stuck in updating state.

**Logs:**
[elastic-agent-diagnostics-2022-12-01T11-22-57Z-00.zip](https://github.com/elastic/elastic-agent/files/10131885/elastic-agent-diagnostics-2022-12-01T11-22-57Z-00.zip)

**Fleet Server logs:**
[Fleet-Server-diagnostics-2022-12-01T11-22-37Z-00.zip](https://github.com/elastic/elastic-agent/files/10131886/Fleet-Server-diagnostics-2022-12-01T11-22-37Z-00.zip)

**Screenshot:**
![3](https://user-images.githubusercontent.com/77374876/205041367-cb3feae6-b576-4861-b1ea-47117b7bbab8.JPG)

**Expected Result:**
Installed secondary agent should get Healthy on installation, on self-managed kibana having Fleet Server running.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by cmacknz** [comment]
There isn't much in the agent logs here, interestingly I can see that the agent thinks it is managed locally which may explain why the status in Fleet isn't being updated:

```json
{"log.level":"info","@timestamp":"2022-12-01T10:09:56.633Z","log.origin":{"file.name":"application/application.go","file.line":80},"message":"Parsed configuration and determined agent is managed locally","ecs.version":"1.6.0"}
```

**Comment by cmacknz** [comment]
In the Fleet server logs I can see the Filestream monitoring instance fail to start after failing to obtain its lock file.

```
{"log.level":"error","@timestamp":"2022-12-01T08:49:25.466Z","message":"Exiting: cannot obtain lockfile: connot start, data directory belongs to process with pid 2612","component":{"binary":"filebeat","dataset":"elastic_agent.filestream_monitoring","id":"filestream-monitoring","type":"filestream"},"ecs.version":"1.6.0","log.origin":{"file.line":1062,"file.name":"instance/beat.go"},"service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-01T08:49:25.466Z","message":"Exiting: cannot obtain lockfile: connot start, data directory belongs to process with pid 2612","component":{"binary":"filebeat","dataset":"elastic_agent.filestream_monitoring","id":"filestream-monitoring","type":"filestream"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-01T08:49:25.492Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":325},"message":"Existing component state changed","component":{"id":"filestream-monitoring","state":"FAILED","message":"Failed: pid '480' exited with code '1'","inputs":[{"id":"filestream-monitoring-filestream-monitoring-agent","state":"FAILED","message":"Failed: pid '480' exited with code '1'"}],"output":{"id":"filestream-monitoring","state":"FAILED","message":"Failed: pid '480' exited with code '1'"}},"ecs.version":"1.6.0"}
```

**Comment by cmacknz** [comment]
I can also see an another of instance of https://github.com/elastic/elastic-agent/issues/1800 in these logs:

```json
{"log.level":"error","@timestamp":"2022-12-01T08:49:33.211Z","message":"Error creating runner from config: No paths were defined for input accessing config","component":{"binary":"filebeat","dataset":"elastic_agent.winlog_default","id":"winlog-default","type":"winlog"},"log.logger":"centralmgmt","log.origin":{"file.line":109,"file.name":"cfgfile/list.go"},"service.name":"filebeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-12-01T08:49:33.211Z","message":"Error creating runner from config: No paths were defined for input accessing config","component":{"binary":"filebeat","dataset":"elastic_agent.winlog_default","id":"winlog-default","type":"winlog"},"log.logger":"centralmgmt","log.origin":{"file.line":109,"file.name":"cfgfile/list.go"},"service.name":"filebeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-12-01T08:49:33.211Z","message":"Error creating runner from config: No paths were defined for input accessing config","component":{"binary":"filebeat","dataset":"elastic_agent.winlog_default","id":"winlog-default","type":"winlog"},"log.logger":"centralmgmt","log.origin":{"file.line":109,"file.name":"cfgfile/list.go"},"service.name":"filebeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
```

This agent is hitting all the bugs it seems.

**Comment by cmacknz** [comment]
Is this reproducible, or is it intermittent?

**Comment by amolnater-qasource** [comment]
Hi @cmacknz 

Thank you for looking into this.
We have revalidated this issue on latest 8.6 BC5 kibana self-managed environment and had below observations:

**Observations:**
- Agent is installed Healthy on Agents tab.
- However there are no Agent logs or data for any integration for this installed agent.
- **The issue is reproducible on all attempts.**

**Build details:**
BUILD: 58693
COMMIT: ed40c16ce9999cc47ad55c11bb097d2e443b31a6

**Agent Logs:**
[elastic-agent-diagnostics-2022-12-06T10-08-31Z-00.zip](https://github.com/elastic/elastic-agent/files/10165017/elastic-agent-diagnostics-2022-12-06T10-08-31Z-00.zip)

**Fleet Server Logs:**
[[Fleet Server]elastic-agent-diagnostics-2022-12-06T10-10-36Z-00.zip](https://github.com/elastic/elastic-agent/files/10165026/Fleet.Server.elastic-agent-diagnostics-2022-12-06T10-10-36Z-00.zip)

Please let us know if anything else is required from our end.
Thanks

**Comment by cmacknz** [comment]
Can we retest this on BC7?

**Comment by simranvaseer-qasource** [comment]
Hi @cmacknz 

We have revalidated this issue on latest 8.6 BC7 kibana self-managed environment and had following observations:

When we are trying to install secondary agent.

**Build Details:**
Build: 58773
Commit: 511e7c66ad8b290feb0af3ea262ab3fb08cc87be
Artifacts: https://staging.elastic.co/8.6.0-75d87829/summary-8.6.0.html

**Observations:**
- Agent is not installed with error -`connection timed out`
![image](https://user-images.githubusercontent.com/102019374/208652952-915b895c-88c6-448a-ba2c-c57a4b18a07e.png)

- Agent is not installed even with `--insecure` flag 
![image](https://user-images.githubusercontent.com/102019374/208653367-0cebd3d1-0daa-4c26-8205-e149fb056084.png)

Please let us know if anything is missing from our end.
Thanks

**Comment by cmacknz** [comment]
If the Fleet server host was set to something other than `0.0.0.0` then this is the expected behaviour, see my comment on https://github.com/elastic/fleet-server/issues/2198#issuecomment-1360720320

**Comment by simranvaseer-qasource** [comment]
Hi @cmacknz 

- Yes, `https://18.234.112.175:8220` is the address of the Fleet Server

- Below are the diagnostics of the agent running on fleet. 

**[elastic-agent-diagnostics-2022-12-21T08-07-36Z-00.zip](https://github.com/elastic/elastic-agent/files/10275746/elastic-agent-diagnostics-2022-12-21T08-07-36Z-00.zip)**

Please let us know if anything else is required from our end.
Thanks

**Comment by michel-laterman** [comment]
I'm unable to recreate this with a self managed stack running BC8.

I have ES + Kibana + fleet-server running on mac OS on one host and the elastic-agent running on a separate ubuntu 22.04 host. It can enroll successfully and appears as healthy in the UI

**Comment by amolnater-qasource** [comment]
Hi @michel-laterman 
We have revalidated this on latest 8.6 BC8 self-managed environment and found the issue as **still reproducible**.

**Observations:**
- ES+Kibana+Fleet Server running on Windows.
- Port 8220 is added in firewall-inbound rules.
- Separate Ubuntu 22.04 agent is installed Unhealthy on self-managed environment, then gets Healthy after 8-10 minutes.
- However, no data under Data Streams is observed for this agent.

**Build details:**
8.6 BC8 self-managed environment
BUILD: 58807
COMMIT: 335b86a633af9ce1d9c8a92187ed1c8697ab139f

**Screenshots:**
![3](https://user-images.githubusercontent.com/77374876/209121427-87cce787-9c97-4074-be6f-7a7e99b07c19.JPG)
![4](https://user-images.githubusercontent.com/77374876/209121430-edffb62d-3d9d-48b4-8437-113636fd5115.JPG)
![image](https://user-images.githubusercontent.com/77374876/209121532-409a370e-da72-4ee2-b016-89051157face.png)

**Ubuntu agent logs:**
[[Ubuntu]elastic-agent-diagnostics-2022-12-22T10-54-46Z-00.zip](https://github.com/elastic/elastic-agent/files/10286383/Ubuntu.elastic-agent-diagnostics-2022-12-22T10-54-46Z-00.zip)

**Fleet Server logs:**

[elastic-agent-diagnostics-2022-12-22T10-53-40Z-00.zip](https://github.com/elastic/elastic-agent/files/10286385/elastic-agent-diagnostics-2022-12-22T10-53-40Z-00.zip)

Please let us know if anything else is required from our end.
Thanks

**Comment by michel-laterman** [comment]
The data shipment issue may have been fixed with https://github.com/elastic/beats/issues/34093
We may need the next snapshots to validate

**Comment by jlind23** [comment]
@amolnater-qasource the next snapshot should be available tomorrow morning your time, we will make sure that one gets trigger today.

**Comment by joshdover** [comment]
I have confirmed that this is fixed on latest builds. Please reopen if reproduced

**Comment by amolnater-qasource** [comment]
Hi @joshdover @jlind23 
We have revalidated this issue on latest 8.6 Snapshot kibana cloud-self-managed environment and found it **still reproducible**.

**Observations:**
- Secondary agent is installed healthy.
- No data and logs for secondary agent installed on self-managed kibana having Fleet Server running.

**Build details:**
BUILD: 58830
COMMIT: 6a5d6d96a534be75fc58acda8f89f2610309d7ff
Artifact: https://snapshots.elastic.co/8.6.0-f6d7d537/downloads/beats/elastic-agent/elastic-agent-8.6.0-SNAPSHOT-windows-x86_64.zip

**Screenshots:**
![3](https://user-images.githubusercontent.com/77374876/209536109-73cdfc48-01bd-4375-872d-cc3216a71032.JPG)
![4](https://user-images.githubusercontent.com/77374876/209536114-05d05c7d-2834-4dce-9604-ac363c4a9601.JPG)
![5](https://user-images.githubusercontent.com/77374876/209536115-dd99bfcb-37f2-435f-874c-bfef3cc41047.JPG)

**Logs:**
[[Second]elastic-agent-diagnostics-2022-12-26T10-05-51Z-00.zip](https://github.com/elastic/elastic-agent/files/10302959/Second.elastic-agent-diagnostics-2022-12-26T10-05-51Z-00.zip)

Could you please confirm if any specific ports need to be added in firewall for windows?
- We are currently adding `8220` inbound rule, as earlier it was working fine with this.

Hence we are **reopening** this issue.

Thanks

**Comment by kpollich** [comment]
I am not able to reproduce this issue in a self-hosted 8.6.0 environment, but I do have an issue with an unhealthy fleet server that may be related? I run my Fleet Server and Elastic Agent via docker in this environment. 

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/6766512/209714448-4113c5d7-ef17-4e94-b797-58933b2ec49f.png">

Something that sticks out in logs: 

```
{"log.level":"error","@timestamp":"2022-12-27T19:33:54.072Z","message":"Error fetching data for metricset beat.stats: monitored beat is using Elasticsearch output but cluster UUID cannot be determined","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"beat/metrics-monitoring","type":"beat/metrics"},"log.origin":{"file.line":256,"file.name":"module/wrapper.go"},"service.name":"metricbeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
```

**Comment by amolnater-qasource** [comment]
Hi @kpollich 
We have revalidated this issue on latest 8.6 Snapshot kibana cloud-self-managed environment and found it **still reproducible**.

**Testing details:**
- Setup self-managed environment on `AWS-Windows-2022-Server`.
- Created `AWS-Ubuntu 2022` and installed secondary agent on this VM.

>I run my Fleet Server and Elastic Agent via docker in this environment.

We are installing Fleet based agents for the test.

**NOTE:**
As per last instructions we used to add `8220` port in inbound rules under the security group and Advanced firewall settings while testing for self-managed Windows OS.
![image](https://user-images.githubusercontent.com/77374876/209807146-ddd8a09c-e18b-42c7-8662-475f790ea9ac.png)
![image](https://user-images.githubusercontent.com/77374876/209807199-5fa7ab2b-6ba4-4670-81da-8673a2e0c0da.png)

**Observations:**
- Secondary agent is installed healthy.
- No data and logs for secondary agent installed on self-managed kibana having Fleet Server running.

**Build details:**
BUILD: 58831
COMMIT: b4a10d435656cddb612f985c4616b3b715ffe7a8

Please let us know if the environment where the issue is reproducible is required.

**Screenshots:**
![image](https://user-images.githubusercontent.com/77374876/209807258-23060eae-3b67-4c09-8ffc-05efb56e5a14.png)
![image](https://user-images.githubusercontent.com/77374876/209810758-fe1d9949-56ba-47bb-ab64-6f1815836e5b.png)

Thanks

**Comment by amolnater-qasource** [comment]
Previously reported issue at https://github.com/elastic/beats/issues/28152
Resolved under https://github.com/elastic/beats/issues/28152#issuecomment-1009693012

**Comment by michalpristas** [comment]
i was running agent from branch and came to the same result as @kpollich 
can you run it with more recent snapshot? the linked [here in a comment](https://github.com/elastic/elastic-agent/issues/1861#issuecomment-1365072975) is couple of fixes short.

**Comment by michel-laterman** [comment]
I'm able to recreate as well

I can run the stack/fleet-server on an ubuntu 22.04 instance in AWS (t3.large) with the following binaries:
```
https://snapshots.elastic.co/8.6.0-7e55dcb1/downloads/elasticsearch/elasticsearch-8.6.0-SNAPSHOT-linux-x86_64.tar.gz
https://snapshots.elastic.co/8.6.0-7e55dcb1/downloads/kibana/kibana-8.6.0-SNAPSHOT-linux-x86_64.tar.gz
https://snapshots.elastic.co/8.6.0-7e55dcb1/downloads/beats/elastic-agent/elastic-agent-8.6.0-SNAPSHOT-linux-x86_64.tar.gz
```
I've observed that it takes a couple minutes for the agent running fleet-server to appear as healthy.
I think it's because the monitoring processes have some issues when initially starting.

When I try to enroll another agent (running on an ubuntu 22.04 t3.micro instance on AWS), I can successfully enroll (passing the `--insecure flag`). However the agent does not send data and appears to be stuck in the `updating` state in the UI with no last checkin activity or last checkin message.
On the terminal we can see that the agent restart appears to have some issues:
```sh
ubuntu@ip-10-0-1-87:~/elastic-agent-8.6.0-SNAPSHOT-linux-x86_64$ sudo systemctl status elastic-agent
● elastic-agent.service - Elastic Agent is a unified agent to observe, monitor and protect your system.
     Loaded: loaded (/etc/systemd/system/elastic-agent.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-12-28 23:25:00 UTC; 1min 12s ago
   Main PID: 1997 (elastic-agent)
      Tasks: 11 (limit: 1113)
     Memory: 146.3M
        CPU: 3.398s
     CGroup: /system.slice/elastic-agent.service
             └─1997 /opt/Elastic/Agent/elastic-agent

Dec 28 23:25:01 ip-10-0-1-87 elastic-agent[1997]: {"log.level":"info","@timestamp":"2022-12-28T23:25:01.460Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/docker.go","file.line":44},"message":"Docker provider skipped, unable to connect: Cannot connec>
Dec 28 23:25:01 ip-10-0-1-87 elastic-agent[1997]: {"log.level":"info","@timestamp":"2022-12-28T23:25:01.461Z","log.origin":{"file.name":"upgrade/upgrade.go","file.line":102},"message":"Source URI reset from \"https://artifacts.elastic.co/downloads/\" to \"https://artifacts.elastic.>
Dec 28 23:25:01 ip-10-0-1-87 elastic-agent[1997]: {"log.level":"info","@timestamp":"2022-12-28T23:25:01.562Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":729},"message":"Updating running component model","ecs.version":"1.6.0"}
Dec 28 23:25:01 ip-10-0-1-87 elastic-agent[1997]: {"log.level":"info","@timestamp":"2022-12-28T23:25:01.829Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new component system/metrics-default: Starting: spawned pid '2018'","component":{>
Dec 28 23:25:01 ip-10-0-1-87 elastic-agent[1997]: {"log.level":"info","@timestamp":"2022-12-28T23:25:01.830Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit system/metrics-default-system/metrics: Starting: spawned pid '2018'","co>
Dec 28 23:25:01 ip-10-0-1-87 elastic-agent[1997]: {"log.level":"info","@timestamp":"2022-12-28T23:25:01.830Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit system/metrics-default: Starting: spawned pid '2018'","component":{"id":>
Dec 28 23:25:02 ip-10-0-1-87 elastic-agent[1997]: {"log.level":"info","@timestamp":"2022-12-28T23:25:02.732Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new component http/metrics-monitoring: Starting: spawned pid '2021'","component":>
Dec 28 23:25:02 ip-10-0-1-87 elastic-agent[1997]: {"log.level":"info","@timestamp":"2022-12-28T23:25:02.736Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit http/metrics-monitoring: Starting: spawned pid '2021'","component":{"id">
Dec 28 23:25:02 ip-10-0-1-87 elastic-agent[1997]: {"log.level":"info","@timestamp":"2022-12-28T23:25:02.736Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit http/metrics-monitoring-metrics-monitoring-agent: Starting: spawned pid >
Dec 28 23:25:02 ip-10-0-1-87 elastic-agent[1997]: {"log.level":"info","@timestamp":"2022-12-28T23:25:02.755Z","log.origin":{"file.name":"cmd/run.go","file.line":237},"message":"reexec shutdown channel triggered","ecs.version":"1.6.0"}
ubuntu@ip-10-0-1-87:~/elastic-agent-8.6.0-SNAPSHOT-linux-x86_64$ sudo ls /opt/Elastic/Agent/data/elastic-agent-88625a/logs/
elastic-agent-20221228.ndjson
ubuntu@ip-10-0-1-87:~/elastic-agent-8.6.0-SNAPSHOT-linux-x86_64$ sudo tail /opt/Elastic/Agent/data/elastic-agent-88625a/logs/elastic-agent-20221228.ndjson
{"log.level":"info","@timestamp":"2022-12-28T23:25:01.460Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/docker.go","file.line":44},"message":"Docker provider skipped, unable to connect: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-28T23:25:01.461Z","log.origin":{"file.name":"upgrade/upgrade.go","file.line":102},"message":"Source URI reset from \"https://artifacts.elastic.co/downloads/\" to \"https://artifacts.elastic.co/downloads/\"","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-28T23:25:01.562Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":729},"message":"Updating running component model","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-28T23:25:01.829Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new component system/metrics-default: Starting: spawned pid '2018'","component":{"id":"system/metrics-default","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-28T23:25:01.830Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit system/metrics-default-system/metrics: Starting: spawned pid '2018'","component":{"id":"system/metrics-default","state":"STARTING"},"unit":{"id":"system/metrics-default-system/metrics","type":"input","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-28T23:25:01.830Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit system/metrics-default: Starting: spawned pid '2018'","component":{"id":"system/metrics-default","state":"STARTING"},"unit":{"id":"system/metrics-default","type":"output","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-28T23:25:02.732Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new component http/metrics-monitoring: Starting: spawned pid '2021'","component":{"id":"http/metrics-monitoring","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-28T23:25:02.736Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit http/metrics-monitoring: Starting: spawned pid '2021'","component":{"id":"http/metrics-monitoring","state":"STARTING"},"unit":{"id":"http/metrics-monitoring","type":"output","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-28T23:25:02.736Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit http/metrics-monitoring-metrics-monitoring-agent: Starting: spawned pid '2021'","component":{"id":"http/metrics-monitoring","state":"STARTING"},"unit":{"id":"http/metrics-monitoring-metrics-monitoring-agent","type":"input","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-28T23:25:02.755Z","log.origin":{"file.name":"cmd/run.go","file.line":237},"message":"reexec shutdown channel triggered","ecs.version":"1.6.0"}
ubuntu@ip-10-0-1-87:~/elastic-agent-8.6.0-SNAPSHOT-linux-x86_64$ sudo elastic-agent status
State: STOPPING
Message: Re-executing
Components: (none)
```
I'm not sure if the re-exec manager or the component runtime is causing the issue in this case, i'll try to run it with debug logs

**Comment by michel-laterman** [comment]
well, without changing anything it worked 🤷

**Comment by michalpristas** [comment]
thanks for diagnostics michel, it looks like a race on agent side with improper cancellation when agent tries to restart/reexec and it keeps hanging. 
will take a look

**Comment by michalpristas** [comment]
@amolnater-qasource please retest tomorrow with SNAPSHOT

**Comment by jlind23** [comment]
+ @dikshachauhan-qasource for awareness

**Comment by michel-laterman** [comment]
I have not been able to recreate

**Comment by jlind23** [comment]
@amolnater-qasource @dikshachauhan-qasource were you able to test it with the latest snapshot available?

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated on latest 8.6 SNAPSHOT self-managed and found it **fixed now**.

**Observations:**
- Secondary agent is installed healthy, gets unhealthy for sometime.
- Data and logs are available for secondary agent installed on self-managed kibana having Fleet Server running.

**Note:**
- We have added ports `8220` and `9200` to inbound rules.

**Current build details:**
8.6 SNAPSHOT
BUILD: 58833
COMMIT: 973aba597166460a5dc6342ac9d975fb30be9075

**Screenshot:**
![3](https://user-images.githubusercontent.com/77374876/210055047-a93a0f07-d696-4474-9bc6-d7d002b8f9d5.JPG)
![4](https://user-images.githubusercontent.com/77374876/210055053-4dd4b8ba-0000-41ac-9069-18f4e7b000d2.JPG)

Hence, we are **closing** this issue and marking it as **QA:Validated**.
Thanks

**Comment by prachigupta-qasource** [comment]
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:
   - https://elastic.testrail.io/index.php?/cases/view/168586
 
Thanks!
