### ISSUE TITLE
Installed agents gets Unhealthy on setting invalid url as default under Fleet Server hosts and even on setting back to valid, agents remains Unhealthy.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#1926]
**Kibana version:**  8.6 BC6 kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
VERSION: 8.6.0 BC6 Kibana cloud environment
BUILD: 58740
COMMIT: f329a77595950244361736dff7208a810299fd69
```

**Preconditions:**
1. 8.6 BC6 kibana cloud environment should be available.
2. Windows, Mac and linux agents should be installed with policy having System integration.

**Steps to reproduce:**
1. Navigate to Fleet>Settings tab.
2. Add invalid url under Fleet Server hosts url: `https://10.10.10.10:8220`.
3. Observe agents goes to Unhealthy state.
4. Now set valid url(hosted fleet server url) back to default.
5. Observe agents remain `UNHEALTHY`. 
6. Restart agent> observe agent still remains Unhealthy.

**Logs:**
[[Same Version]elastic-agent-diagnostics-2022-12-12T11-50-44Z-00.zip](https://github.com/elastic/elastic-agent/files/10207638/Same.Version.elastic-agent-diagnostics-2022-12-12T11-50-44Z-00.zip)

**Screenshot:**
![8](https://user-images.githubusercontent.com/77374876/207038507-2a008fe7-220d-4990-8810-a553f584b8ba.JPG)

https://user-images.githubusercontent.com/77374876/207038528-4f37713a-e76e-4a78-b00e-e0f61f40b750.mp4

**Expected Result:**
Installed agents gets Unhealthy on setting invalid url as default under Fleet Server hosts[Expected], however on setting back to valid, agents should get back to `HEALTHY` state.

**Comment by amolnater-qasource** [comment]
Similar issue at https://github.com/elastic/elastic-agent/issues/257

**Comment by cmacknz** [comment]
There was a bug similar to this that should have been resolved in https://github.com/elastic/elastic-agent/pull/1329. It looked like files involved were unmodified as part of the V2 merge.

**Comment by amolnater-qasource** [comment]
Hi @cmacknz @michalpristas 
We have revalidated this issue on latest 8.6 Snapshot kibana cloud-staging environment and found it **still reproducible**.

**Observations:**
- Installed agents gets Unhealthy on setting invalid url as default under Fleet Server hosts and even on setting back to valid, agents remains Unhealthy.

**Build details:**
BUILD: 58830
COMMIT: 6a5d6d96a534be75fc58acda8f89f2610309d7ff
Artifact: https://snapshots.elastic.co/8.6.0-f6d7d537/downloads/beats/elastic-agent/elastic-agent-8.6.0-SNAPSHOT-windows-x86_64.zip

**Screenshots:**
![9](https://user-images.githubusercontent.com/77374876/209664945-c7cd7fb2-150a-41e4-9465-0cf781f91918.JPG)


**Logs:**
[[Output]elastic-agent-diagnostics-2022-12-27T12-01-20Z-00.zip](https://github.com/elastic/elastic-agent/files/10308042/Output.elastic-agent-diagnostics-2022-12-27T12-01-20Z-00.zip)


Hence we are **reopening** this issue.

Thanks

**Comment by michalpristas** [comment]
this is in fact not related, see different last checkin message 
previously it was `failed to connect to 10.10.10.10.:8220` now it's `1 or more component/unit in failed state` 

i created an issue for what we're seeing here: https://github.com/elastic/elastic-agent/issues/2018
closing in favor of mentioned issue

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.6 BC10 Kibana cloud environment and found it **fixed** now.
- Installed agents gets Unhealthy on setting invalid url as default under Fleet Server hosts[Expected], however on setting back to valid, agents gets back to HEALTHY state.

**Build details:**
BUILD: 58852
COMMIT: d3a625ef4a6e611a5b3233a1ce5cbe8ef429eb47

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/211269932-2f75b3c9-6936-44a6-bc82-3e42fa3063b0.mp4

![8](https://user-images.githubusercontent.com/77374876/211269989-5e67faf1-82ef-46c4-90d7-712a61946382.JPG)

Hence, marking this issue as **QA:Validated**.

Thanks

**Comment by prachigupta-qasource** [comment]
### `Bug Conversion:`

We have updated **01 testcase** for this scenario in our fleet test suite at:
  - https://elastic.testrail.io/index.php?/cases/view/168386

Thanks!
