### ISSUE TITLE
[Agent-Upgrade 8.6.1>8.6.2]: Agent gets unhealthy on triggering upgrade and error `Unable to clean downloads before update`, however gets successfully upgraded.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#2273]
**Kibana version:** 8.6.2 BC2 Kibana cloud environment

**Host OS:** All

**Build details:**
VERSION: 8.6.2 BC2 
BUILD: 59020
COMMIT: aabd37e8a9069bed4f63b8c457a6829f4581ab97
Artifact Link: https://www.elastic.co/downloads/past-releases/elastic-agent-8-6-1

**Preconditions:**
1. 8.6.2BC2 Kibana cloud environment should be available.
2. Agent Policy should be available with System and Endpoint defend integrations.

**Steps to reproduce:**
1. Install lower version 8.6.1 agents using agent policy.
2. Add BC artifact link under Fleet>Settings>Agent binary: `https://staging.elastic.co/8.6.2-ca679c34/downloads/`
3. Trigger agent upgrade from Fleet-UI and observe agent gets into Updating>Unhealthy state.
4. Observe error log `Unable to clean downloads before update`.
5. However, agent gets upgraded to 8.6.2 and also gets Healthy.

**Note:**
- This issue is reproducible on Mac, Linux and Windows VMs multiple times on different builds.

**Screenshots:**
![1](https://user-images.githubusercontent.com/77374876/218972701-5914e386-cd79-4e6e-bd38-13e4cbea7694.JPG)
![2](https://user-images.githubusercontent.com/77374876/218971814-075993ef-2990-45e9-8cf4-d19512ff3c8d.JPG)
![3](https://user-images.githubusercontent.com/77374876/218971816-47f893b4-8286-410e-8c55-109780f17afb.JPG)
![4](https://user-images.githubusercontent.com/77374876/218971818-9c1e95d2-a22c-4938-bd9f-499123a2e5c5.JPG)

**Logs:**
[[Upgrade]elastic-agent-diagnostics-2023-02-15T07-52-45Z-00.zip](https://github.com/elastic/elastic-agent/files/10740868/Upgrade.elastic-agent-diagnostics-2023-02-15T07-52-45Z-00.zip)

**Expected Result:**
On triggering upgrade agent should get in Updating state and then should directly get into Healthy state with latest version.

**Related issue with Unhealthy agents:**
https://github.com/elastic/elastic-agent/issues/2272

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by cmacknz** [comment]
The attached diagnostics only include the logs from the healthy 8.6.2 agent, I can't tell why the previous 8.6.1 version would have been unhealthy. 

The diagnostics command only collects logs for the currently running agent. Manually creating a zip file of the agent installation directory is the only way to get logs from both the previous and current versions right now.

**Comment by amolnater-qasource** [comment]
Hi @cmacknz 

Thank you for looking into this.
We have copied all the available logs under Elastic/Agent folder and created below zip files. 

**Logs:**
[Logs under Elastic-Agent.zip](https://github.com/elastic/elastic-agent/files/10752569/Logs.under.Elastic-Agent.zip)
[[elastic-agent-913c02]elastic-agent-20230216-4.zip](https://github.com/elastic/elastic-agent/files/10752570/elastic-agent-913c02.elastic-agent-20230216-4.zip)
[[elastic-agent-b8553c]Logs.zip](https://github.com/elastic/elastic-agent/files/10752571/elastic-agent-b8553c.Logs.zip)


Please let us know if anything else is required from end.
Thanks

**Comment by cmacknz** [comment]
Thanks I see a checkin error in the logs right before the upgrade happens:

```json
{"log.level":"warn","@timestamp":"2023-02-16T05:20:07.129Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":190},"message":"Possible transient error during checkin with fleet-server, retrying","log":{"source":"elastic-agent"},"error":{"message":"fail to checkin to fleet-server: all hosts failed: 1 error occurred:\n\t* requester 0/1 to host https://347f18d104d142d4a3be1403d5fe870f.fleet.europe-west1.gcp.cloud.es.io:443/ errored: Post \"https://347f18d104d142d4a3be1403d5fe870f.fleet.europe-west1.gcp.cloud.es.io:443/api/fleet/agents/ce4fd704-6dc2-4945-b389-7e91efb9dfa8/checkin?\": context canceled\n\n"},"request_duration_ns":45821998793,"failed_checkins":1,"retry_after_ns":82299101016,"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-02-16T05:20:07.129Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":207},"message":"checkin retry loop was stopped","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"
```

I believe this was fixed with https://github.com/elastic/elastic-agent/pull/2203 in 8.6.2. This should not be reproducible for an upgrade from 8.6.2 to 8.7.0-SNAPSHOT.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.10.0 SNAPSHOT kibana cloud environment and found it **still reproducible**.

**Observations:**
- Agent gets unhealthy on just before upgrade for sometime, however later gets successfully upgraded and gets back Healthy.
  - Agent upgraded from 8.8.2>8.9.0

**Screen Recording:**

https://github.com/elastic/elastic-agent/assets/77374876/c4b55595-0da1-49be-884e-f5c26d710cfc

**Logs:**
[elastic-agent-dc443b-logs.zip](https://github.com/elastic/elastic-agent/files/12290141/elastic-agent-dc443b-logs.zip)
[elastic-agent-cdc5ba-logs.zip](https://github.com/elastic/elastic-agent/files/12290140/elastic-agent-cdc5ba-logs.zip)

**Build details:**
VERSION: 8.10.0 SNAPSHOT
BUILD: 65561
COMMIT: 4dadcbb91136a3e7d39e4b419aa12e21a37e4918


Please let us know if anything else is required from our end.

Thanks!

**Comment by amolnater-qasource** [comment]
Hi Team,

We have reproduced this issue on latest 8.10.0 SNAPSHOT kibana cloud environment and collected the logs below:

**Logs:**
[elastic-agent-diagnostics-2023-08-10T06-52-53Z-00.zip](https://github.com/elastic/elastic-agent/files/12309698/elastic-agent-diagnostics-2023-08-10T06-52-53Z-00.zip)


**Agent Json:**
[ip-172-31-82-68-agent-details.zip](https://github.com/elastic/elastic-agent/files/12309697/ip-172-31-82-68-agent-details.zip)


**Screen Recording:**

https://github.com/elastic/elastic-agent/assets/77374876/ca8d57e5-9825-472e-8bd8-95078b365e7e



**Build details:**
VERSION: 8.10.0 SNAPSHOT
BUILD: 65796
COMMIT: 4637b744d80686a2f9cbdfaf2f8b24a0c92f79c8

Please let us know if anything else is required from our end.

Thanks!

**Comment by cmacknz** [comment]
Thanks the agent appears to show has having reported itself as DEGRADED in Fleet with all components healthy looking at the agent details document:

```json
  "last_checkin": "2023-08-10T06:52:24Z",
  "last_checkin_status": "DEGRADED",
  "last_checkin_message": "Upgrading to version 8.9.0",
  "components": [
    {
      "id": "log-default",
      "type": "log",
      "status": "HEALTHY",
      "message": "Healthy: communicating with pid '1814'",
      "units": [
        {
          "id": "log-default-logfile-system-d1fe6aee-7c6c-4cac-a4ab-3844da1bb779",
          "type": "input",
          "status": "HEALTHY",
          "message": "Healthy"
        },
        {
          "id": "log-default",
          "type": "output",
          "status": "HEALTHY",
          "message": "Healthy"
        }
      ]
    },
    {
      "id": "system/metrics-default",
      "type": "system/metrics",
      "status": "HEALTHY",
      "message": "Healthy: communicating with pid '1820'",
      "units": [
        {
          "id": "system/metrics-default-system/metrics-system-d1fe6aee-7c6c-4cac-a4ab-3844da1bb779",
          "type": "input",
          "status": "HEALTHY",
          "message": "Healthy"
        },
        {
          "id": "system/metrics-default",
          "type": "output",
          "status": "HEALTHY",
          "message": "Healthy"
        }
      ]
    },
    {
      "id": "http/metrics-monitoring",
      "type": "http/metrics",
      "status": "HEALTHY",
      "message": "Healthy: communicating with pid '1833'",
      "units": [
        {
          "id": "http/metrics-monitoring-metrics-monitoring-agent",
          "type": "input",
          "status": "HEALTHY",
          "message": "Healthy"
        },
        {
          "id": "http/metrics-monitoring",
          "type": "output",
          "status": "HEALTHY",
          "message": "Healthy"
        }
      ]
    },
    {
      "id": "filestream-monitoring",
      "type": "filestream",
      "status": "HEALTHY",
      "message": "Healthy: communicating with pid '1841'",
      "units": [
        {
          "id": "filestream-monitoring-filestream-monitoring-agent",
          "type": "input",
          "status": "HEALTHY",
          "message": "Healthy"
        },
        {
          "id": "filestream-monitoring",
          "type": "output",
          "status": "HEALTHY",
          "message": "Healthy"
        }
      ]
    },
    {
      "id": "beat/metrics-monitoring",
      "type": "beat/metrics",
      "status": "HEALTHY",
      "message": "Healthy: communicating with pid '1849'",
      "units": [
        {
          "id": "beat/metrics-monitoring-metrics-monitoring-beats",
          "type": "input",
          "status": "HEALTHY",
          "message": "Healthy"
        },
        {
          "id": "beat/metrics-monitoring",
          "type": "output",
          "status": "HEALTHY",
          "message": "Healthy"
        }
      ]
    }
  ],
```

Interestingly the agent reports itself as Upgrading to Fleet when it reports that message:

https://github.com/elastic/elastic-agent/blob/ebf2fe72ac1e4b589aeee5f5a5fc92bd9acf8e33/internal/pkg/agent/application/coordinator/coordinator.go#L446

**Comment by cmacknz** [comment]
The agent doesn't handle the Upgrading state when it translates the agent state to the Fleet state:

https://github.com/elastic/elastic-agent/blob/ebf2fe72ac1e4b589aeee5f5a5fc92bd9acf8e33/internal/pkg/agent/application/gateway/fleet/fleet_gateway.go#L382-L393

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.10.0 BC7 kibana cloud environment and had below observations:

**Observations:**
- On triggering upgrade agent gets in Updating state and then directly get into Healthy state with latest version.
- No Unhealthy agent status is observed.

**Screen Recording:**

https://github.com/elastic/elastic-agent/assets/77374876/2d5a9d72-2d05-4f4e-be56-d82cff8920cf


**Build details:**
VERSION: 8.10.0 BC7
BUILD: 66350
COMMIT: 824bcbfd9972c61e79ca9def6d43b550c5ff2999

Hence we are marking this issue as **QA:Validated**.

Thanks!
