### ISSUE TITLE
[French-German]: Agent service is not restarted itself on installation for French and German Windows 10.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#3960]
**Kibana Build details:**
```
VERSION: 8.12.0 BC3
BUILD: 69985
COMMIT: 2a8afed8572a4c709aa1c64216748197eeb9b18f
Artifact Link: https://staging.elastic.co/8.12.0-61156bc6/summary-8.12.0.html
```

**Host OS:**  Windows French and German

**Preconditions:**
1. 8.12.0 BC3 Kibana cloud environment should be available.

**Steps to reproduce:**
1. Run agent install command on Windows 10 French/German VM.
2. Observe agent service is not restarted itself on installation.
3. Navigate to services and manually restart the Elastic Agent service.
4. Observe agent gets Healthy under Agents tab.

**NOTE:**
- Issue is consistently reproducible on French and German VMs.
- Issue is not reproducible on Korean and Spanish VMs.

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/d1c44fba-07c3-467d-9cf9-d7e889130c45)
![image](https://github.com/elastic/elastic-agent/assets/77374876/662ce37a-73d7-41f1-bd5b-61171cc7f574)

**Expected Result:**
Agent service should be restarted itself on installation for French and German Windows 10.

**Logs:**
Unable to collect logs till manually restarted:
![image](https://github.com/elastic/elastic-agent/assets/77374876/d3b0ef1e-8f4d-495b-b00b-24c67d1181e3)

**Logs after restart:**
[elastic-agent-diagnostics-2023-12-27T08-05-55Z-00.zip](https://github.com/elastic/elastic-agent/files/13776780/elastic-agent-diagnostics-2023-12-27T08-05-55Z-00.zip)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by intxgo** [comment]
Hello, interestingly this is not a new bug, straight from an elevated console of my Windows 11 Pro English OS:

```
PS C:\Users\[redacted]> & 'C:\Program Files\Elastic\Agent\elastic-agent.exe' diagnostics
[WARNING]: failed to fetch agent diagnostics: error in DiagnosticAgent RPC call: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: open \\\\.\\pipe\\elastic-agent-system: The system cannot find the file specified."[WARNING]: failed to fetch unit diagnostics: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: open \\\\.\\pipe\\elastic-agent-system: The system cannot find the file specified."[WARNING]: failed to fetch component diagnostics: error in DiagnosticComponents RPC call: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: open \\\\.\\pipe\\elastic-agent-system: The system cannot find the file specified."Error: failed collecting diagnostics: no diags could be fetched
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.10/fleet-troubleshooting.html
PS C:\Users\[redacted]> & 'C:\Program Files\Elastic\Endpoint\elastic-endpoint.exe' diagnostics
Created endpoint diagnostics output located at C:\WINDOWS\TEMP\endpoint-diagnostics-a36684.zip

PS C:\Users\[redacted]> & 'C:\Program Files\Elastic\Endpoint\elastic-endpoint.exe' version
version: 8.10.4, compiled: Wed Oct 11 19:00:00 2023, branch: HEAD, commit: 8442397386468c4ab954a0a34406e209336efa7b
PS C:\Users\[redacted]> & 'C:\Program Files\Elastic\Agent\elastic-agent.exe' version
Binary: 8.10.4 (build: a92ca32b922dc62e45b532600a8562ee1c82205f at 2023-10-12 09:09:48 +0000 UTC)
Daemon: <failed to communicate>
could not get version. failed to communicate with running daemon: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: open \\\\.\\pipe\\elastic-agent-system: The system cannot find the file specified."
Use --binary-only flag to skip trying to retrieve version from running daemon
```

**Comment by cmacknz** [comment]
We have had this bug before:

- https://github.com/elastic/elastic-agent/issues/857

**Comment by cmacknz** [comment]
https://github.com/elastic/elastic-agent/issues/857#issuecomment-1280839185

**Comment by cmacknz** [comment]
The original fix was in https://github.com/elastic/elastic-agent/pull/1552/files

It's not clear yet what caused the regression.

**Comment by leehinman** [comment]
This is in the logs:

```
"log.level":"warn","@timestamp":"2023-12-27T07:56:47.860Z","log.logger":"control","log.origin":{"file.name":"server/listener_windows.go","file.line":49},"message":"failed to detect admin: %!w(*fmt.wrapError=&{failed to get current user groups: Der Benutzername konnte nicht gefunden werden. 2221})","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
```

I **think** that is "Username could not be found"

https://github.com/elastic/elastic-agent/blob/08610da63060da5c9f934b901c0cea04a36c96d0/pkg/control/v2/server/listener_windows.go#L70

**Comment by leehinman** [comment]
Failing to get groups for the user that was returned by `GetCurrent()` seems weird, but clearly it is happening.  I think we should probably switch to the method for detecting Windows admin [here](https://github.com/golang/go/issues/28804).

@amolnater-qasource is it possible for me to get access to the German language VM?

**Comment by cmacknz** [comment]
Interestingly we already have the code at the end of that comment chain in the agent but we aren't using it on this path:

https://github.com/elastic/elastic-agent/blob/08610da63060da5c9f934b901c0cea04a36c96d0/pkg/utils/root_windows.go#L14-L43

**Comment by leehinman** [comment]
https://github.com/elastic/elastic-agent/pull/3988 is untested since I don't have a German VM

**Comment by amolnater-qasource** [comment]
Hi @leehinman 

Thank you for looking into this.

We are cloning the Windows German template available on [GCP](https://console.cloud.google.com/compute/instances?project=elastic-security-dev) project: `elastic-security-dev` for testing this.

Please let us know if anything else is required from our end.

Thanks!

**Comment by leehinman** [comment]
> We are cloning the Windows German template available on [GCP](https://console.cloud.google.com/compute/instances?project=elastic-security-dev) project: `elastic-security-dev` for testing this.

I tried to create a vm using the german image.  the vm is called `leh-win-german-test`, I set the Windows passord, and then try to RDP but I get an error, see below.  Any ideas on what to change?

<img width="259" alt="Screenshot 2024-01-03 at 14 19 19" src="https://github.com/elastic/elastic-agent/assets/57081003/9883a2be-1584-4b60-a9c8-bc5e6366c61f">

**Comment by leehinman** [comment]
https://github.com/elastic/security-team/tree/main/tools/sec-eng-prod/sep-vms was a huge help in getting the VM setup, tested and #3988 fixes it for me.

**Comment by jlind23** [comment]
@amolnater-qasource Would you be able to test this again please?

**Comment by amolnater-qasource** [comment]
Hi Team,

Thank you for the fixes.
We have revalidated this issue on latest 8.12.0 BC5 kibana cloud environment and found it **fixed now**.

**Observations:**
-  Agent service is restarted itself on installation for French and German Windows 10.

**Build details:**
VERSION: 8.12.0
BUILD: 70053
COMMIT: db9b8921b37139cbb1e11d23f6381f655edeb72b
Artifact Link: https://staging.elastic.co/8.12.0-9f05a310/downloads/beats/elastic-agent/elastic-agent-8.12.0-windows-x86_64.zip

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/8fc070ce-b5f4-4964-8287-7536e23f4ec7)

Hence we are **closing** this issue and marking as **QA:Validated**.

Thanks!

**Comment by harshitgupta-qasource** [comment]
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:
   - https://elastic.testrail.io/index.php?/cases/view/149944
 
Thanks!

**Comment by yomduf** [comment]
Hello team, this seems not fixed, I tested  it on a 8.12.2 agent on windows 10 Pro (French) Vm and running the diag end in result
```
[C:\Program](file:///C:/Program) Files\Elastic\Agent>elastic-agent.exe diagnostics
[WARNING]: failed to fetch agent diagnostics: error in DiagnosticAgent RPC call: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: open [\\\\.\\pipe\\elastic-agent-system](file:///pipe//elastic-agent-system): The system cannot find the file specified."[WARNING]: failed to fetch unit diagnostics: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: open [\\\\.\\pipe\\elastic-agent-system](file:///pipe//elastic-agent-system): The system cannot find the file specified."[WARNING]: failed to fetch component diagnostics: error in DiagnosticComponents RPC call: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: open [\\\\.\\pipe\\elastic-agent-system](file:///pipe//elastic-agent-system): 
The system cannot find the file specified."Error: failed collecting diagnostics: no diags could be fetched
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.12/fleet-troubleshooting.html
```

**Comment by cmacknz** [comment]
That might be a different error, since I don't see any French or German localized text in that error message and there is in the original issue that was fixed here.

**Comment by cmacknz** [comment]
Closing again, @yomduf please open a new issue with your error.
