### ISSUE TITLE
[SLES 15]: No "system.auth" logs for system integration under Data Streams tab for SLES 15 linux agent.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#4495]
**Kibana version:** 7.15.0 BC-2 Kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
Build: 43742
Commit: 113d5f2a745ab9be7d567d13ff906dfd0f5b7a9a
Artifact Link: https://staging.elastic.co/7.15.0-d7816905/downloads/beats/elastic-agent/elastic-agent-7.15.0-linux-x86_64.tar.gz
```

**Preconditions:**
1. 7.15.0 BC-2 Kibana cloud environment should be available.
2. An SLES 15 linux agent must be installed with Default policy having System integration.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Data Streams tab.
3. Select `System` from Integration dropdown and `logs` from type dropdown.

**Logs:**
[logs.zip](https://github.com/elastic/integrations/files/7044131/logs.zip)

**Expected Result:**
"system.auth" logs should be generated for system integration under Data Streams tab for SLES 15 agent.

**Screenshot:**
![13](https://user-images.githubusercontent.com/77374876/130736666-9814dffc-bf95-4e61-9ea8-1456e458924b.JPG)

**Note:**
This issue is **not observed for Ubuntu 20** machines with .tar artifact.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.14.0 Snapshot kibana cloud environment and found it **still reproducible on SLES 15**.

**Observations:**
-  No `system.auth` logs for system integration under Data Streams tab for SLES 15 linux agent.


**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/9a72a977-2603-4f46-80e5-a77efb24cd3c)


**Build details:**
VERSION: 8.14.0 SNAPSHOT
BUILD: 72779
COMMIT: ea309fdbf7ed02d5a8872daf56132b9e40e60982

**Agent Logs:**
[elastic-agent-diagnostics-2024-03-28T07-32-42Z-00.zip](https://github.com/elastic/elastic-agent/files/14785621/elastic-agent-diagnostics-2024-03-28T07-32-42Z-00.zip)

Please let us know if anything else is required from our end.
Thanks!!

**Comment by amolnater-qasource** [comment]
JFI @pierrehilbert

**Comment by pierrehilbert** [comment]
For me this is the same case than https://github.com/elastic/elastic-agent/issues/3650 will be covered when https://github.com/elastic/beats/issues/37086 will be done.

**Comment by nimarezainia** [comment]
do we think that this is now resolved because of https://github.com/elastic/integrations/pull/11618 ??

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 9.1.0-SNAPSHOT kibana cloud environment and found it **still reproducible**.

**Observations:**
-  No "system.auth" logs for system integration under Data Streams tab for SLES 15 linux agent.

**Screenshot:**

![Image](https://github.com/user-attachments/assets/433bca0a-8587-42b7-aef6-db79eb79d211)

**Build details:**
VERSION: 9.1.0-SNAPSHOT
BUILD: 86016
COMMIT: dc7f543fda54204ae6e784322b78dafddee2545b
Artifact Link: https://snapshots.elastic.co/9.1.0-72d8a512/downloads/beats/elastic-agent/elastic-agent-9.1.0-SNAPSHOT-linux-x86_64.tar.gz

Please let us know if anything else is required from our end.

Thanks!!

**Comment by pierrehilbert** [comment]
From what I can see in https://github.com/elastic/integrations/pull/11618 it has not been enabled by default for SLES 15.
To confirm, could you please update the `Collect logs from system instances using journald` section with `${host.os_version} == "12 (bookworm)" or (${host.os_platform} == "amzn" and ${host.os_version} == "2023") or (${host.os_platform} == "sles" and ${host.os_version} == "15-SP6")`

**Comment by amolnater-qasource** [comment]
Hi @pierrehilbert 

Thank you for sharing the details.
We have revalidated this issue by manually adding the required configurating under `Collect logs from system instances using journald` and found it **fixed now**.

**Observations:**
- "system.auth" logs is generated for system integration under Data Streams tab for SLES 15 agent.

**Screenshot:**

![Image](https://github.com/user-attachments/assets/51c6bfec-1a3e-46f9-8ea7-c22416cfdfd9)


**Build details:**
VERSION: 9.1.0-SNAPSHOT
BUILD: 86016
COMMIT: dc7f543fda54204ae6e784322b78dafddee2545b
Artifact Link: https://snapshots.elastic.co/9.1.0-9b9a9358/downloads/beats/elastic-agent/elastic-agent-9.1.0-SNAPSHOT-linux-x86_64.tar.gz

Hence, we are closing and marking this issue as **QA:Validated**.

Thanks!

**Comment by cmacknz** [comment]
Re-opening, we need to change the default condition in the integration with the change from https://github.com/elastic/elastic-agent/issues/4495#issuecomment-2841703521
