### ISSUE TITLE
Agent is unable to retry upgrade with correct binary on failing once with incorrect binary.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#7611]
**Kibana Build details:**
```
VERSION: 9.0.0 BC1
BUILD: 84280
COMMIT: 4297a07fabcb4fcf3958d63762f54b03b47eba84
```
Artifact Link: https://staging.elastic.co/8.18.0-181f11b6/summary-8.18.0.html#elastic-agent-package

**Preconditions:**
1. 9.0.0-BC1 Kibana cloud environment should be available.
2. 8.18.0 BC10 agent should be installed.

**Steps to reproduce:**
1. Add invalid agent binary and trigger agent upgrade to `9.0.0`.
2. Observe after 15 minutes, agent upgrade gets failed.
3. Update the correct binary and wait for changes to get updated under policy.
4. Restart upgrade to `9.0.0` again.
5. Observe agent fails to upgrade to 9.0.0.

**NOTE:**
- Issue is consistently reproducible.
- No issue is observed on directly upgrading with correct agent binary.

**Expected Result:**
Agent should be upgraded successfully on retrying upgrade with correct binary when failed once with incorrect binary.

**Screen Recording:**

https://github.com/user-attachments/assets/2f0b7f8d-546c-4187-8c4a-58002f677822

**Logs:**

[elastic-agent-diagnostics-2025-03-28T09-47-05Z-00.zip](https://github.com/user-attachments/files/19503582/elastic-agent-diagnostics-2025-03-28T09-47-05Z-00.zip)
[elastic-agent-diagnostics-2025-03-28T09-15-14Z-00.zip](https://github.com/user-attachments/files/19503603/elastic-agent-diagnostics-2025-03-28T09-15-14Z-00.zip)
[elastic-agent-diagnostics-2025-03-28T08-35-50Z-00.zip](https://github.com/user-attachments/files/19503602/elastic-agent-diagnostics-2025-03-28T08-35-50Z-00.zip)

**Agent JSON:**
[EC2AMAZ-DUAF4CI-agent-details.zip](https://github.com/user-attachments/files/19503588/EC2AMAZ-DUAF4CI-agent-details.zip)

**Comment by amolnater-qasource** [comment]
@muskangulati-qasource Please review.

**Comment by pierrehilbert** [comment]
@pchila maybe you could have a look here to check what's happening?

**Comment by pchila** [comment]
From a quick look at logs in [elastic-agent-diagnostics-2025-03-28T09-47-05Z-00.zip](https://github.com/user-attachments/files/19503582/elastic-agent-diagnostics-2025-03-28T09-47-05Z-00.zip)
 
We can see that we are using a wrong agent binary download settings for 9.0.0 BC1
```
{"log.level":"info","@timestamp":"2025-03-28T09:05:25.378Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.(*Upgrader).Reload","file.name":"upgrade/upgrade.go","file.line":124},"message":"Source URI changed from \"https://artifacts.elastic.co/downloads/\" to \"https://artifacts.elastic.co/downloads/\"","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
```
so we cannot download the artifact
```
{"log.level":"info","@timestamp":"2025-03-28T09:08:51.969Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).logUpgradeDetails","file.name":"coordinator/coordinator.go","file.line":594},"message":"updated upgrade details","log":{"source":"elastic-agent"},"upgrade_details":{"target_version":"9.0.0","state":"UPG_DOWNLOADING","action_id":"2906c360-b8cc-4952-8381-32417348ab11","metadata":{"retry_error_msg":"unable to download package: package 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-8.18.0-63b735\\downloads\\elastic-agent-9.0.0-windows-x86_64.zip' not found: open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-8.18.0-63b735\\downloads\\elastic-agent-9.0.0-windows-x86_64.zip: The system cannot find the file specified.\ncall to 'https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-9.0.0-windows-x86_64.zip' returned unsuccessful status code: 404","retry_until":"2025-03-28T11:08:51.7706282Z"}},"ecs.version":"1.6.0"}
```

This is correct since the 9.0.0 artifacts are not yet published on 'https://artifacts.elastic.co/downloads/beats/'

@amolnater-qasource did you set the correct source URI as specified in the 9.0.0 BC1 report here https://staging.elastic.co/9.0.0-9c59c3a0/summary-9.0.0.html ?

**Comment by amolnater-qasource** [comment]
Hi @pchila 
Yes, we have updated the agent binary, yet the restart upgrade doesn't work.

For some reason the binary isn't getting updated under the agent after upgrade is failed with incorrect binary: `https://artifacts.elastic.co/downloads/beats/` and agent is not using new(the correct) binary on retry upgrade.

Please find below elastic-agent.yml for the same:
[elastic-agent.zip](https://github.com/user-attachments/files/19504331/elastic-agent.zip)

We were consistently able to observe this issue, when even on setting the correct agent binary the agent failed to upgrade to the latest version.

**Screen Recording:**

https://github.com/user-attachments/assets/17f4a935-9b69-4868-acf7-d2d47d14ba9a


Further, we encountered this issue while upgrading 8.18.0 BC10 kibana with agents to 9.0.0 BC1.

Please let us know if we are missing anything here.

Thanks!!

**Comment by muskangulati-qasource** [comment]
Secondary review is Done for this ticket!

**Comment by amolnater-qasource** [comment]
Hi Team,

Please find below logs for another re-test with a different incorrect binary: https://artifxxts.elastic.co/downloads/

**Logs:**
[elastic-agent-diagnostics-2025-03-28T12-00-24Z-00.zip](https://github.com/user-attachments/files/19505002/elastic-agent-diagnostics-2025-03-28T12-00-24Z-00.zip)


**Screen Recording:**

https://github.com/user-attachments/assets/97adcb0a-8e86-4663-a229-54fd3f57d80e


Thanks!

**Comment by ebeahan** [comment]
I tried to reproduce, but in my testing I was able to download & upgrade from 8.18.0 BC10 to 9.0.0 BC1 successfully.

`09:48:02.155 elastic_agent [elastic_agent][info] download from https://staging.elastic.co/9.0.0-9c59c3a0/downloads/beats/elastic-agent/elastic-agent-9.0.0-windows-x86_64.zip completed in 8 seconds @ 39.47MBps`

How are you restarting the upgrade after the failure using the incorrect binary?

**Comment by amolnater-qasource** [comment]
Hi Team,

While testing agent upgrade retry[8.18.3 BC1>9.0.3 BC1] testcase on 9.0.3 BC1, we have observed this issue still reproducible.

**Observations:**
- Agent is unable to retry upgrade with correct binary on failing once with incorrect binary.


**Build details:**
VERSION: 9.0.3
BUILD: 84935
COMMIT: 3b8379b249b9b5ab0c3c2ee245cd7d62ad93ab4d

**Impacted Testcase:**
- [Validate that agent retries to upgrade after failing with incorrect agent binary and upgrades successfully on retrying with correct binary.](https://elastic.testmo.net/runs/view/449?group_id=2430&test_id=6927530)

**Feature:** https://github.com/elastic/ingest-dev/issues/1995

Please let us know if anything else is required from our end.
Thanks!!

**Comment by ebeahan** [comment]
thanks for confirming the issue persists @amolnater-qasource. Will prioritize in a future iteration.

**Comment by michel-laterman** [comment]
Some key logs, we can see the 1st upgrade fail:
```
{"log.level":"info","@timestamp":"2025-03-31T06:30:59.379Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.cleanNonMatchingVersionsFromDownloads","file.name":"upgrade/cleanup.go","file.line":21},"message":"Cleaning up non-matching downloaded versions","log":{"source":"elastic-agent"},"version":"8.18.0","downloads.path":"C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-8.18.0-fba248\\downloads","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2025-03-31T06:30:59.381Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/actions/handlers.(*Upgrade).Handle.func1","file.name":"handlers/handler_action_upgrade.go","file.line":79},"message":"upgrade to version 9.0.0 failed: failed download of agent binary: unable to download package: package 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-8.18.0-fba248\\downloads\\elastic-agent-9.0.0-windows-x86_64.zip' not found: open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-8.18.0-fba248\\downloads\\elastic-agent-9.0.0-windows-x86_64.zip: The system cannot find the file specified.\nfetching package failed: Get \"https://artifxxts.elastic.co/downloads/beats/elastic-agent/elastic-agent-9.0.0-windows-x86_64.zip\": lookup artifxxts.elastic.co: no such host","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2025-03-31T06:30:59.381Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).logUpgradeDetails","file.name":"coordinator/coordinator.go","file.line":594},"message":"updated upgrade details","log":{"source":"elastic-agent"},"upgrade_details":{"target_version":"9.0.0","state":"UPG_FAILED","action_id":"f2962f4a-7460-415b-a245-88058dce179a","metadata":{"retry_error_msg":"unable to download package: package 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-8.18.0-fba248\\downloads\\elastic-agent-9.0.0-windows-x86_64.zip' not found: open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-8.18.0-fba248\\downloads\\elastic-agent-9.0.0-windows-x86_64.zip: The system cannot find the file specified.\nfetching package failed: Get \"https://artifxxts.elastic.co/downloads/beats/elastic-agent/elastic-agent-9.0.0-windows-x86_64.zip\": lookup artifxxts.elastic.co: no such host","retry_until":"2025-03-31T08:17:03.5225164Z","failed_state":"UPG_DOWNLOADING","error_msg":"failed download of agent binary: unable to download package: package 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-8.18.0-fba248\\downloads\\elastic-agent-9.0.0-windows-x86_64.zip' not found: open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-8.18.0-fba248\\downloads\\elastic-agent-9.0.0-windows-x86_64.zip: The system cannot find the file specified.\nfetching package failed: Get \"https://artifxxts.elastic.co/downloads/beats/elastic-agent/elastic-agent-9.0.0-windows-x86_64.zip\": lookup artifxxts.elastic.co: no such host"}},"ecs.version":"1.6.0"}

```

Then we see the artifacts location being corrected
```
{"log.level":"info","@timestamp":"2025-03-31T06:36:18.300Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.(*Upgrader).Reload","file.name":"upgrade/upgrade.go","file.line":124},"message":"Source URI changed from \"https://artifxxts.elastic.co/downloads/\" to \"https://staging.elastic.co/9.0.0-58178eb3/downloads/\"","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
```

Finally we see what I think is issue:
```
{"log.level":"error","@timestamp":"2025-03-31T06:36:37.356Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/dispatcher.(*ActionDispatcher).reportNextScheduledUpgrade","file.name":"dispatcher/dispatcher.go","file.line":336},"message":"failed to get start time for scheduled upgrade action [id = 05f80366-711e-47db-8fcb-5e68e3364a5d]","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
...
{"log.level":"info","@timestamp":"2025-03-31T06:42:18.897Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/actions/handlers.(*Upgrade).getAsyncContext","file.name":"handlers/handler_action_upgrade.go","file.line":130},"message":"Duplicate upgrade to version 9.0.0 received","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
```

After the 1st upgrade action fails, (I think) it is still being persisted locally by the agent instead of cleared.
So when the 2nd upgrade action comes in, it is detected as a duplicate and dropped.

**Comment by pierrehilbert** [comment]
@ebeahan should we continue to run our smoke tests on this as this will continue to fail until we are fixing it?

**Comment by ebeahan** [comment]
> @ebeahan should we continue to run our smoke tests on this as this will continue to fail until we are fixing it?

I'd rather prioritize fixing - will try to add to upcoming iteration.

**Comment by cmacknz** [comment]
Possibly this was fixed by https://github.com/elastic/elastic-agent/pull/9634.

Can we retest against the latest snapshot (any branch, it was backported to all of them) to confirm?

**Comment by amolnater-qasource** [comment]
Hi @cmacknz 
Thank you for the update.

We have revalidated this issue by upgrading latest 9.1.4-SNAPSHOT agent to 9.2.0-SNAPSHOT and found it **still reproducible**.

**Observations:**
- Agent is unable to retry upgrade with correct binary on failing once with incorrect binary. 

**Screen Captures:**

https://github.com/user-attachments/assets/7580d7bd-b44d-4ce6-ad95-5407c8cce9b3


https://github.com/user-attachments/assets/d76e311e-7766-4ba6-836e-0c52ef60f049


https://github.com/user-attachments/assets/a0e3441a-d051-4d28-9378-5b8610a3ac0d


<img width="906" height="210" alt="Image" src="https://github.com/user-attachments/assets/cbf0db79-c463-4f55-9ba3-56bc1c66464f" />


**Agent Logs:**
[elastic-agent-diagnostics-2025-09-16T07-15-31Z-00.zip](https://github.com/user-attachments/files/22358542/elastic-agent-diagnostics-2025-09-16T07-15-31Z-00.zip)

**JSON:**
[ip-172-31-30-101-agent-details.json.zip](https://github.com/user-attachments/files/22358548/ip-172-31-30-101-agent-details.json.zip)


**Artifact Link:**
https://snapshots.elastic.co/9.1.4-9f5fb45a/downloads/beats/elastic-agent/elastic-agent-9.1.4-SNAPSHOT-linux-x86_64.tar.gz

<img width="906" height="70" alt="Image" src="https://github.com/user-attachments/assets/842f5830-8ccf-4195-90a6-b98d33278ee2" />

Please let us know if anything else is required from our end.
Thanks!

**Comment by ebeahan** [comment]
> I'd rather prioritize fixing - will try to add to upcoming iteration.

After revisiting with @michel-laterman - there's more work involved here than will be completed short term. Let's remove this from our smoke testing for now until we're able to properly address.

**Comment by cmacknz** [comment]
The `failed to notify units of proxied action` here has now appeared in several support cases. It seems like notifying endpoint to have it unprotect itself is not idempotent, and doing this notification multiple times in a row caused endpoint to return an error, which is a fatal error. 

https://github.com/elastic/elastic-agent/pull/9634 doesn't seem to have caused this instead it seems like it made it detectable.

I think this test case is definitely valid and is probably something we should fold into our own automated testing in an upgrade with defend installed.
